/*
    DRVCONF.H -- Driver Configuration for USNET
    Copyright (C) 1994 United States Software Corporation
    Generated by USNCFG based on NETCONF.C hosts:
      test  test2  
*/


/*
   NETCONF.C Driver Usage
   Defined to 0 if mentioned but NOTUSED

   wrap     to talk to self, for testing
   WD8003   Western Digital Ethernet board
   NE1000   Novell 1000 Ethernet interface
   NE2000   Novell 2000 Ethernet interface
   _3C503   3COM 503 Ethernet driver
   _3C509   3COM 509 Ethernet driver
   NE2100   Novell 2100 Ethernet interface
   EXP16    Intel EtherExpress 16-bit interface
   EN360    Motorola 68360 Ethernet
   MB86960  Fujitsu 86960 Ethernet
   DPRIM    Datapoint RIM ARCNET board
   I8250    PC serial ports
   H64180   Hitachi 64180 on-chip serial
   HC11SCI  Motorola HC11 on-chip serial
   HC16SCI  Motorola HC16 on-chip serial
   D2681    DUART 2681 serial
*/

#define	WD8003	&WD8003_T
extern PTABLE	WD8003_T;

#define	NE2000	&NE2000_T
extern PTABLE	NE2000_T;

#define	NE2100 0

#define	EXP16	&EXP16_T
extern PTABLE	EXP16_T;

#define	EN360 0

#define	MB86960 0

#define	I8250	&I8250_T
extern PTABLE	I8250_T;

#define	H64180 0

#define	HC11SCI 0

#define	HC16SCI 0

#define	D2681 0


/*
   NETCONF.C Adapter Usage
   Defined to 0 if mentioned but NOTUSED
     The adapter code is called before driver initialization, and
     after driver shutdown.  This mechanism allows us to use the same exact
     driver in different hardware environments.
   PCMCIA1  PCMCIA adapter for card services
   PCMCIA2  PCMCIA adapter for socket services
*/
